### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by sbweeden** [IBM-Security/IBM-Verify-FreeRADIUS#1]
When trying to build the free radius server (3.0.15) after copying across the rlm_verify directory:

src/modules/rlm_verify/rlm_verify.c:26:22: fatal error: sdk/isam.h: No such file or directory
compilation terminated.
scripts/boiler.mk:635: recipe for target 'build/objs/src/modules/rlm_verify/rlm_verify.lo' failed
make: *** [build/objs/src/modules/rlm_verify/rlm_verify.lo] Error 1

**Comment by jaredpage-ibm** [comment]
Hi Shane, 

This error should have been resolved in commit 2d40fc5763bb1627ebe0d6831b316d3c1d7b4144.
Please let me know if you run into it again and if this is okay to close.

**Comment by sbweeden** [comment]
Closing - was able to build against 3.0.15.
